# Exercise 3. - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  

Check out [Alcohol Consumption Exercises Video Tutorial](https://youtu.be/az67CMdmS6s) to watch a data scientist go through the exercises


### Step 1. Import the necessary libraries

In [28]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [29]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'
dataset = pd.read_csv(url)
dataset.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 3. Assign it to a variable called drinks.

In [30]:
drinks = dataset
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [31]:
drinks.groupby('continent').beer_servings.mean().sort_values(ascending=False).head(1)

continent
EU    193.777778
Name: beer_servings, dtype: float64

### Step 5. For each continent print the statistics for wine consumption.

In [39]:
drinks.groupby('continent').wine_servings.describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [41]:
drinks.groupby('continent').agg({
    'beer_servings': 'mean',
    'wine_servings': 'mean',
    'spirit_servings': 'mean'
})

           beer_servings  wine_servings  spirit_servings
continent
AF             61.471698      16.264151        16.339623
AS             37.045455       9.068182        60.840909
EU            193.777778     142.222222       132.555556
OC             89.687500      35.625000        58.437500
SA            175.083333      62.416667       114.750000

### Step 7. Print the median alcohol consumption per continent for every column

In [ ]:
drinks.groupby('continent').agg({
    'beer_servings': 'median',
    'wine_servings': 'median',
    'spirit_servings': 'median'
})

           beer_servings  wine_servings  spirit_servings
continent
AF                  32.0            2.0              3.0
AS                  17.5            1.0             16.0
EU                 219.0          128.0            122.0
OC                  52.5            8.5             37.0
SA                 162.5           12.0            108.5

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [44]:
drinks.groupby('continent').spirit_servings.agg(['min', 'max', 'mean'])

           min  max        mean
continent
AF           0  152   16.339623
AS           0  326   60.840909
EU           0  373  132.555556
OC           0  254   58.437500
SA          25  302  114.750000